### ISSUE TITLE
3.0 SDK compatibility issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-toolbox-for-mac#28]
```
What steps will reproduce the problem?
1. Starting with working unit tests using 2.2.1 SDK, use 3.0 GM SDK
2. Variety of issues: bad CPU, BPT trap, etc.
3.

What is the expected output? What do you see instead?
Expect build success, rather than compilation errors and test framework 
problems.

What version of the product are you using? On what operating system?
1.5.1 of GTM on OS X 10.5.7 with iPhone OS SDK 3.0 GM

Please provide any additional information below.
If someone can comment that they have this working with 3.0 SDK, I'll try a bit 
more, but just 
seems like the switch to 3.0 broke GTM iPhone unit tests.

```

Original issue reported on code.google.com by `aaronmiller@gmail.com` on 20 Jun 2009 at 1:53
