### ISSUE TITLE
Does not compile with Apple LLVM 4.0 in Xcode 4.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-toolbox-for-mac#81]
```
What steps will reproduce the problem?
1. Upgrade to Xcode 4.5
2. Make sure the compiler is LLVM 4.0 (instead of GCC) for your project target
3. Build a project that uses Google-Toolbox

What is the expected output? What do you see instead?
Expected: Should compile without errors
Actual result: Compile errors:
GTMObjC2Runtime.m:32:15: No member named 'name' in 'struct objc_class'
GTMObjC2Runtime.m:46:22: No member named 'protocols' in 'struct objc_class'
GTMObjC2Runtime.m:46:64: Incomplete definition of type 'struct 
objc_protocol_list'
GTMObjC2Runtime.m:47:32: Incomplete definition of type 'struct 
objc_protocol_list'
GTMObjC2Runtime.m:48:18: Incomplete definition of type 'struct 
objc_protocol_list'
GTMObjC2Runtime.m:58:15: No member named 'super_class' in 'struct objc_class'
GTMObjC2Runtime.m:74:20: 'class_nextMethodList' is unavailable
GTMObjC2Runtime.m:75:14: Incomplete definition of type 'struct objc_method_list'
GTMObjC2Runtime.m:77:64: Incomplete definition of type 'struct objc_method_list'
GTMObjC2Runtime.m:82:30: Incomplete definition of type 'struct objc_method_list'
GTMObjC2Runtime.m:83:34: Incomplete definition of type 'struct objc_method_list'
GTMObjC2Runtime.m:85:19: Incomplete definition of type 'struct objc_method_list'
GTMObjC2Runtime.m:98:16: Incomplete definition of type 'struct objc_method'
GTMObjC2Runtime.m:103:16: Incomplete definition of type 'struct objc_method'
GTMObjC2Runtime.m:122:20: Incomplete definition of type 'struct objc_method'
GTMObjC2Runtime.m:123:11: Incomplete definition of type 'struct objc_method'

What version of the product are you using? On what operating system?
Xcode 4.5 with LLVM 4.0 on Mac OS X 10.7.4

Please provide any additional information below.
```

Original issue reported on code.google.com by `tmanand@gmail.com` on 12 Jun 2012 at 8:57
