### ISSUE TITLE
GTM failed to compile using SDK 10.6 - Needs adoption of deprecated API starting from 10.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-toolbox-for-mac#49]
```
GTM compile phase using base SDK 10.6 shows a number of errors saying that
specific API used in GTM is deprecated starting from 10.6.

Steps to reproduce:
1. open GTM.xcodeproj project
2. select SnowLeopardOrLater-Debug configuration
3. select UnitTest-Foundation target
4. cmd+B to run compilation and tests

Expected result:
compilation succeed without errors (and warnings), tests passed

Actual result:
compilation failed with a number of errors reported

OS: Mac OS X 10.6.3 (10D573)
Xcode - v. 3.2.2 with iPhone SDK
(Component versions: Xcode IDE: 1650.0 Xcode Core: 1648.0 ToolSupport: 1631.0)
GTM - checkout of trunk r:335.

Please see errors reported in attached file.

```

Original issue reported on code.google.com by `sergey.maysak` on 25 Apr 2010 at 9:35

Attachments:
- [gtm 10.6sdk deprecated API log.rtf](https://storage.googleapis.com/google-code-attachments/google-toolbox-for-mac/issue-49/comment-0/gtm 10.6sdk deprecated API log.rtf)
